name: .NET

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - uses: actions/checkout@v3
    # Install .NET 6.0
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore
    # Build project
    - name: Build
      run: dotnet build --no-restore
    # Run Tests
    - name: Test
      run: dotnet test --no-build --verbosity normal

    # Generate the website
    - name: Publish
      run: dotnet publish ekapturio.csproj -c Release -o release --nologo

    # Publish the website
    - name: GitHub Pages action
      if: ${{ github.ref == 'refs/heads/main' }} # Publish only when the push is on master
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        BRANCH: main
        FOLDER: release/wwwroot
        repository_name: ekapturio/ekapturio.github.io



      # uses: peaceiris/actions-gh-pages@v3.6.1
      # with:
      #   repository_name: ekapturio/ekapturio.github.io
      #   github_token: ${{ secrets.PUBLISH_TOKEN }}
      #   publish_branch: main
      #   publish_dir: bin/Release/net6.0/wwwroot
      #   allow_empty_commit: false
      #   keep_files: false
      #   force_orphan: true
      #   # TODO uncomment the following line if you have a custom domain name
      #   # cname: demo.meziantou.net
