name: .NET

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - uses: actions/checkout@v3
   
    # Install .NET 6.0
    - name: Install .NET 6.0
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
   
    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore
    
    # Build project
    - name: Build
      run: dotnet build --no-restore
    
    # Run Tests
    - name: Test
      run: dotnet test --no-build --verbosity normal

    # Find and replace MudBlazor.min.css reference
    - name: Find and replace MudBlazor.min.css reference
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "_content/MudBlazor/MudBlazor.min.css"
        replace: "css/mud-blazor/MudBlazor.min.css"
        regex: false
      
    # Find and replace MudBlazor.min.js reference
    - name: Find and replace MudBlazor.min.js reference
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "_content/MudBlazor/MudBlazor.min.js"
        replace: "js/mud-blazor/MudBlazor.min.js"
        regex: false

    # Generate website
    - name: Generate website
      run: 
        dotnet publish ekapturio.csproj -c Release -o release -p:GHPages=true --nologo
      
    # Copy auto-generated css file 
    - name: Copy auto-generated ekapturio.styles.css file
      run:
        cp obj/Debug/net6.0/scopedcss/bundle/. bin/Release/net6.0/wwwroot -r
        
    # Copy all files from wwwroot folder
    - name: Copy files wwwroot folder
      run:
        cp wwwroot/. bin/Release/net6.0/wwwroot -r
        
    # add .nojekyll file
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll

    # Publish to Github Pages
    - name: GitHub Pages action
      if: ${{ github.ref == 'refs/heads/main' }} # Publish only when the push is on master
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        external_repository: ekapturio/ekapturio.github.io
        personal_token: ${{ secrets.PUBLISH_TOKEN }}
        publish_branch: gh-pages
        publish_dir: bin/Release/net6.0/wwwroot
        allow_empty_commit: false
        keep_files: true
        force_orphan: true
      #   # TODO uncomment the following line if you have a custom domain name
      #   # cname: demo.meziantou.net