name: .NET

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - uses: actions/checkout@v3
    # Install .NET 6.0
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore
    # Build project
    - name: Build
      run: dotnet build --no-restore
    # Run Tests
    - name: Test
      run: dotnet test --no-build --verbosity normal
